files: [
    {
        "escape_quotes" : 0,
        "escape_special_characters" : 0,
        "languages_mapping" : {
            "locale" : {
                ar: "ar",
                bg: "bg",
                ca: "ca",
                cs: "cs",
                da: "da",
                de: "de",
                de-AT: "de_AT",
                de-CH: "de_CH",
                el: "el",
                en: "en",
                en-AU: "en_AU",
                en-CA: "en_CA",
                en-GB: "en_GB",
                en-IE: "en_IE",
                es: "es",
                es-AR: "es_AR",
                es-CO: "es_CO",
                es-MX: "es_MX",
                et: "et",
                eu: "eu",
                fa: "fa",
                fi: "fi",
                fr: "fr",
                fr-BE: "fr_BE",
                fr-CA: "fr_CA",
                fr-CH: "fr_CH",
                gl: "gl",
                he: "iw",
                hi-IN: "hi_IN",
                hr: "hr",
                hr-BA: "hr_BA",
                hu: "hu",
                id: "in",
                it: "it",
                it-CH: "it_CH",
                ja: "ja",
                kk: "kk",
                km: "km",
                ko: "ko",
                lo: "lo",
                lt: "lt",
                mk: "mk",
                ms: "ms",
                my: "my",
                nb: "nb",
                nl: "nl",
                nl-BE: "nl_BE",
                pl: "pl",
                pt-BR: "pt_BR",
                pt-PT: "pt_PT",
                ro: "ro",
                ru: "ru",
                sk: "sk",
                sl: "sl",
                sr-RS: "sr_RS",
                sr-RS-latin: "sr_RS_latin",
                sv: "sv",
                ta-IN: "ta_IN",
                th: "th",
                tr: "tr",
                uk: "uk",
                vi: "vi",
                zh-CN: "zh_CN",
                zh-TW: zh_TW
            }
        },
        "skip_untranslated_strings" : 1,
        "source" : "**/Language.properties",
        "translation" : "**/%file_name%_%locale%.%file_extension%"
    }
]