jobs:
    crowdin-upload-sources:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout specific folder
                uses: actions/checkout@v4
                with:
                    sparse-checkout: |
                        modules/apps/portal-language/portal-language-lang/src/main/resources/content
                    sparse-checkout-cone-mode: false
            -   name: Move Language.properties to root
                run: mv --force modules/apps/portal-language/portal-language-lang/src/main/resources/content ./Language.properties
            -   name: "Debugging"
                run: ls -la .
            -   env:
                    CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
                    CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
                name: Crowdin push
                uses: crowdin/github-action@v2
                with:
                    download_translations: false
                    upload_sources: true
                    upload_sources_args: >
                        --branch=LPD-50198
                        --auto-update
                        --verbose
                    upload_translations: false
name: Crowdin Upload Sources
on:
    push:
        branches: [LPD-50198]
        # paths: ['modules/apps/portal-language/portal-language-lang/src/main/resources/content/Language.properties']